#!/bin/bash
container=$1

cat >> /var/lib/lxc/$container/config << EOF
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0
lxc.network.name = eth0
#lxc.start.auto = 1
#lxc.start.delay = 0
EOF

macaddr=$(echo $container|md5sum|sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
echo "lxc.network.hwaddr = $macaddr" >> /var/lib/lxc/$container/config
echo "lxc.network.hwaddr = $macaddr"



echo "lxc.hook.pre-mount = /var/lib/lxc/$container/mount-overlay" >> /var/lib/lxc/$container/config





cat >> /var/lib/lxc/$container/mount-overlay << "EOF"
#!/bin/sh
LXC_DIR=$(dirname "$LXC_ROOTFS_PATH")
mkdir $LXC_DIR/upper $LXC_DIR/template $LXC_DIR/work
mount -o ro "$LXC_DIR/template.squashfs" "$LXC_DIR/template"
modprobe overlay
cd $LXC_DIR
mount -t overlay overlay -olowerdir=template,upperdir=upper,workdir=work rootfs
EOF

chmod a+x /var/lib/lxc/$container/mount-overlay
